// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx86zvk4Y5aH7k1KZGJY_OXb9Bwc9GkLE',
    appId: '1:206327220012:web:5e3eb7fbf58c8eb9444e89',
    messagingSenderId: '206327220012',
    projectId: 'armario-virtual-4c54d',
    authDomain: 'armario-virtual-4c54d.firebaseapp.com',
    storageBucket: 'armario-virtual-4c54d.firebasestorage.app',
    measurementId: 'G-WH6TPXF0P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZujQBEXU7t19Sut3-73M98kyKdCU1k8',
    appId: '1:206327220012:android:cd8dc2c3265a963e444e89',
    messagingSenderId: '206327220012',
    projectId: 'armario-virtual-4c54d',
    storageBucket: 'armario-virtual-4c54d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqSyVZ3HZgz5Y-NUAqvQJG1mLjFoB0cI',
    appId: '1:206327220012:ios:b3089bb35571a5ef444e89',
    messagingSenderId: '206327220012',
    projectId: 'armario-virtual-4c54d',
    storageBucket: 'armario-virtual-4c54d.firebasestorage.app',
    androidClientId: '206327220012-72d2n14osd7tuvnic0ni84u7e75tnne7.apps.googleusercontent.com',
    iosClientId: '206327220012-s3kdh23kkm0d8qkgic74qasrmhlgfldd.apps.googleusercontent.com',
    iosBundleId: 'com.aleramirez.armariovirtual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqSyVZ3HZgz5Y-NUAqvQJG1mLjFoB0cI',
    appId: '1:206327220012:ios:a9f5c5a4e53aa60d444e89',
    messagingSenderId: '206327220012',
    projectId: 'armario-virtual-4c54d',
    storageBucket: 'armario-virtual-4c54d.firebasestorage.app',
    iosBundleId: 'com.aleramirez.armariovirtual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx86zvk4Y5aH7k1KZGJY_OXb9Bwc9GkLE',
    appId: '1:206327220012:web:d19af290cb301944444e89',
    messagingSenderId: '206327220012',
    projectId: 'armario-virtual-4c54d',
    authDomain: 'armario-virtual-4c54d.firebaseapp.com',
    storageBucket: 'armario-virtual-4c54d.firebasestorage.app',
    measurementId: 'G-KR8RWL4RSE',
  );
}